# Generated by Django 5.0.2 on 2024-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(0, 'What role are you?'), (1, 'Client'), (2, 'Pilot')], max_length=25),
        ),
    ]
