# Generated by Django 5.0.2 on 2024-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('What role are you?', 0), ('Client', 1), ('Pilot', 2)], help_text='What role are you?', max_length=25),
        ),
    ]
