# Generated by Django 5.0.2 on 2024-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0002_city_country_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
