# Generated by Django 5.0.2 on 2024-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
