# Generated by Django 5.0.2 on 2024-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0007_profile_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
