# Generated by Django 5.0.2 on 2024-04-23 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0008_alter_profile_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequestModel',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=150)),
                ('request_email', models.EmailField(max_length=254)),
                ('request_address', models.CharField(max_length=250)),
                ('request_extra_information', models.TextField(blank=True)),
                ('request_pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_page.profile')),
                ('request_job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_page.jobtype')),
            ],
        ),
    ]
