# Generated by Django 5.0.2 on 2024-04-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0009_jobtype_jobrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestmodel',
            name='request_tel',
            field=models.CharField(default=123456, help_text='Enter your phone number', max_length=13),
            preserve_default=False,
        ),
    ]
