# Generated by Django 5.0.2 on 2024-04-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0011_remove_jobrequestmodel_request_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestmodel',
            name='request_country',
            field=models.ForeignKey(help_text='Enter a country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_page.country'),
        ),
    ]
