# Generated by Django 5.0.2 on 2024-04-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0012_alter_jobrequestmodel_request_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestmodel',
            name='request_country',
            field=models.ForeignKey(default='Select Country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_page.country'),
        ),
    ]
