# Generated by Django 5.0.2 on 2024-04-23 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0014_alter_jobrequestmodel_request_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestmodel',
            name='request_create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrequestmodel',
            name='request_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
