# Generated by Django 5.0.2 on 2024-04-24 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0015_jobrequestmodel_request_create_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReviewModel',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_comment', models.TextField(max_length=500)),
                ('review_create_date', models.DateTimeField(auto_now_add=True)),
                ('review_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='drone_page.jobrequestmodel')),
                ('review_pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
