# Generated by Django 5.0.2 on 2024-04-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_page', '0016_jobreviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreviewmodel',
            name='review_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drone_page.profile'),
        ),
    ]
